Outst/urls.py
from django.conf.urls import url, include
from .import views

app_name = 'Outst'

urlpatterns = [
    url(r'^new/$', views.NewForm.as_view(), name='new-form'),

    url(r'^thanks/$', views.thankyou, name='thankyou'),

    url(r'^hey/$', views.Hey, name='hey'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^$', views.LoginForm.as_view(), name='login'),

    url(r'^logout/$', views.logout, name='logout'),

    url(r'^list/$', views.IndexView.as_view(), name='list'),

    url(r'^welcome/$', views.NewForm.as_view(), name='welcome'),

    url(r'^(?P<pk>[0-9]+)/$', views.ItemAdd.as_view(), name='detail'),

    url(r'^applist/$', views.AppIndexView.as_view(), name='applist'),

]

Outstationform/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^outst/', include('Outst.urls')),
]

Outst/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Info(models.Model):
    name = models.CharField(max_length=250)
    roomno = models.CharField(max_length=250)
    bitsid = models.CharField(max_length=250)
    destination = models.CharField(max_length=250)
    leavingdate = models.DateField()
    returningdate = models.DateField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Outst:thankyou')


class Approved(models.Model):
    name = models.CharField(max_length=250)
    accepted = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Outst:thankyou')

Outst/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Outst/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views import generic
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import auth
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Info, Approved


def Hey(request):
    return render(request, 'Outst/welcome.html')


# Create your views here.
class NewForm(CreateView):
    model = Info
    fields = ['name', 'roomno', 'bitsid', 'destination', 'leavingdate', 'returningdate']


def thankyou(request):
    return render(request, 'Outst/thankyou.html')


class UserFormView(View):

    form_class = UserForm
    template_name = 'Outst/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    # request.user.username       display their username
                    return redirect('Outst:hey')
        return render(request, self.template_name, {'form': form})

error = False


class LoginForm(View):

    form_class = UserForm
    template_name = 'Outst/login_form.html'

    def get(self, request):
        form = self.form_class(None)
        if error:
            return render(request, self.template_name, {'form': form}, {'error': error})
        else:
            return render(request, self.template_name, {'form': form})

    def post(self, request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)

        if user is not None and user.is_active:
            # Correct password, and the user is marked "active"
            auth.login(request, user)
            # Redirect to a success page.
            if user.is_staff:
                return HttpResponseRedirect("/outst/list/")
            else:
                return HttpResponseRedirect("/outst/hey/")
        else:
            # Show an error page
            error = True
            return HttpResponseRedirect("/outst/", {'error': error})


def logout(request):
    auth.logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect("/outst/")


class IndexView(generic.ListView):
    template_name = 'Outst/index.html'

    def get_queryset(self):
        return Info.objects.all()


class DetailView(generic.DetailView):
    model = Info
    template_name = 'Outst/detail.html'


class ItemAdd(CreateView):
    model = Approved
    fields = ['name', 'accepted', 'date', 'mealtype']
    template_name = 'Outst/add_to_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_pk = self.kwargs['pk']
        product = Info.objects.get(pk=product_pk)
        context.update({
            'product': product
        })
        return context


class AppIndexView(generic.ListView):
    template_name = 'Outst/Appindex.html'

    def get_queryset(self):
        return Approved.objects.all()

templates/Outst/Appindex.html
{% extends 'Outst/base.html' %}

{%  block body %}
    {% if object_list %}
        <h3>Your previous requests are</h3>
        <ul>
            {% for items in object_list %}

            <li><a href="">{{ items.name }} ---- {{ items.date }} ---- {{ items.mealtype }}</a>

            {% endfor %}
        </ul>
    {% else %}
        <h3>You dont have any previous requests</h3>
    {% endif %}



{% endblock %}

templates/Outst/add_to_cart.html
{%  extends 'Outst/base.html' %}

{% block body %}

<h3>Do you really want to give your consent ?</h3>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {%  csrf_token %}
        <input type="hidden" name="name" value="{{ product.name }}">
        <input type="hidden" name="accepted" value="Yes">
         <input type="hidden" name="date" value="{{ product.date }}">
         <input type="hidden" name="mealtype" value="{{ product.mealtype }}">

       <button type="submit" class="btn btn-success"> Allow</button>



    </form>





{% endblock %}

templates/Outst/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}Outstation{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'Outst/style.css' %}" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>




</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">Outstation Form</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="">
                    <a href="">
                        <span class="" aria-hidden="true"></span>&nbsp;

                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left"  role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right" >
            {% if request.user.is_authenticated  %}
                <li class="">
                    <a href="">
                        <span class="glyphicons glyphicons-calendar" aria-hidden="true"></span>
                        Calendar
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'Outst:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        SignOut
                    </a>
                </li>
             {% else %}
                 <li class="">
                    <a href="{% url 'Outst:login' %}">
                        <span class="glyphicons glyphicons-calendar" aria-hidden="true"></span>
                        Calendar
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'Outst:login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Login
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'Outst:register' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        SignUp
                    </a>
                </li>
                {% endif %}


            </ul>

        </div>


    </div>
</nav>
{%  block body %}
{% endblock %}



</body>
</html>

templates/Outst/detail.html
{% extends 'Outst/base.html' %}

<title>{%  block title %}Students{% endblock %}</title>

{%  block body %}


    <h1>{{ items.name}}</h1>
    <h2><a href=""></a></h2>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}




{% endblock %}

templates/Outst/form-template.html
{%  for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{  field }}</div>
        </div>
{% endfor %}

templates/Outst/index.html
{% extends 'Outst/base.html' %}

{%  block body %}
    {% if object_list %}
        <h3>Following requests are available - </h3>
        <ul>
            {% for items in object_list %}
            <li><a href="{% url 'Outst:detail' items.id %}">{{ items.name }} ---- {{ items.destination }}</a>

            {% endfor %}
        </ul>
    {% else %}
        <h3>No new requests</h3>
    {% endif %}



{% endblock %}

templates/Outst/info_form.html
{%  extends 'Outst/base.html' %}
{%  block title %}Fill Outstation Form{%  endblock %}
{%  block album_active %}active{% endblock %}

{%  block body %}
    <div class="container-fluid">

        <div class="row">

            <div class = "ool-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                         {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                         {% endif %}

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {%  csrf_token %}
                            {%  include 'Outst/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>



                    </div>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

templates/Outst/login_form.html
{%  extends 'Outst/base.html' %}
{%  block title %}Login{%  endblock %}



{%  block body %}
    <div class="container-fluid">

        <div class="row">

            <div class = "ool-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% for err in error %}
                        {% if err %}
                        <p class="error">Sorry, that's not a valid username or password</p>
                        {% endif %}
                        {% endfor %}
                        <form action="" method="post">
                            {%  csrf_token %}
                            <div class="form-group">
                                <label  class="control-label col-sm-2" for="username">User name:</label>
                                <input type="text" name="username" value="" id="username"><br><br><br>
                                <label  class="control-label col-sm-2" for="password">Password:</label>
                                <input type="password" name="password" value="" id="password"><br><br><br>
                                <input class="control-label col-sm-2" type="submit" value="login" />
                                <input type="hidden" name="next" value="{{ next|escape }}" /><br><br>

                                 <h4> New to this site then <a href="{% url 'Outst:register' %}">SignUp</a> </h4>
                            </div>
                        </form>
    {{ err }}
 {%  endblock %}

templates/Outst/registration_form.html
{%  extends 'Outst/base.html' %}
{%  block title %}Register{%  endblock %}
{%  block album_active %}active{% endblock %}

{%  block body %}

    <div class="container-fluid">

        <div class="row">

            <div class = "ool-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a new Account</h3>
                         {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                         {% endif %}

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {%  csrf_token %}
                            {%  include 'Outst/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>


                        <h4> Or if you are already a user then <a href="{% url 'Outst:login' %}">SignIn</a> </h4>



                    </div>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

templates/Outst/thankyou.html
{%  extends 'Outst/base.html' %}

{% block body %}

<h5>Your request has been submitted .Kindly visit <a href="{% url 'Outst:applist' %}">Check previous requests</a></h5>
    to check status.
{% endblock %}

templates/Outst/welcome.html
{%  extends 'Outst/base.html' %}

{% block body %}
<br>
    <br>
    <br>
<a href="{% url 'Outst:applist' %}">Check previous requests</a>
<br>
    <br>
    <br>
    <br>
    <br>

<a href="{% url 'Outst:new-form' %}">File new request</a>

{% endblock %}